### ISSUE TITLE
"'Controller' not found" when the project namespace has been changed

### ISSUE THREAD

**Issue by macecchi** [Laravel-Backpack/LogManager#9] opened 2017-02-02 00:20 UTC
Hi,

Because I have customised my project's namespace to be something other than `App` (using `php artisan app:name`), [this line](https://github.com/Laravel-Backpack/LogManager/blob/master/src/app/Http/Controllers/LogController.php#L5) in `LogController` throws an exception saying that `Controller` was not found.

A simple solution would be to make `LogController` extend from the default controller, like `CrudController` and other classes from Backpack do.

So that line would change from:

```php
use App\Http\Controllers\Controller;
```

to:

```php
use Illuminate\Routing\Controller;
```

**Comment by tabacitu** [comment] 2017-08-30 20:01
Hi @macecchi ,

I see this has been fixed a long time ago, but the issue is still open. Closing it now. Thanks for the report and solution.

Cheers!

**Closed as completed by tabacitu** 2017-08-30 20:01 UTC

**Comment by macecchi** [comment] 2017-08-30 20:03
Thanks for the update, @tabacitu! Have a nice day :)
